name: Smart Auto Commit

on:
  schedule:
    - cron: "0 6,9,12,15,18,21,23 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Random decision
        id: decide
        run: |
          SHOULD_COMMIT=$((RANDOM % 3))
          echo "should_commit=$SHOULD_COMMIT" >> $GITHUB_OUTPUT

      - name: Generate commits
        if: steps.decide.outputs.should_commit != '0'
        run: |
          COUNT=$(( (RANDOM % 6) + 1 ))

          echo "Fazendo $COUNT commits..."

          for i in $(seq 1 $COUNT)
          do
            echo "Atualizado em $(date) - commit $i" >> log.txt

            git config --global user.name "github-actions"
            git config --global user.email "actions@github.com"

            git add .
            git commit -m "auto commit $i"

            sleep $(( (RANDOM % 20) + 1 ))
          done

          git push
