name: Auto Commit

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update file
        run: |
          echo "Atualizado em $(date)" >> log.txt

      - name: Commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "auto commit" || echo "sem mudanças"
          git push
